// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPEjZCzCRMGyYVsa_d98o74l5wux6VCXQ',
    appId: '1:144680558728:web:f0f893ecadb97186557f3d',
    messagingSenderId: '144680558728',
    projectId: 'widgetmaster999',
    authDomain: 'widgetmaster999.firebaseapp.com',
    databaseURL: 'https://widgetmaster999-default-rtdb.firebaseio.com',
    storageBucket: 'widgetmaster999.appspot.com',
    measurementId: 'G-DVMKYKKF4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtujCqfGxOauj0dwEasn8WjM4ufy9qCUE',
    appId: '1:144680558728:android:170c6a52bc2c8c35557f3d',
    messagingSenderId: '144680558728',
    projectId: 'widgetmaster999',
    databaseURL: 'https://widgetmaster999-default-rtdb.firebaseio.com',
    storageBucket: 'widgetmaster999.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6_sfCoPdtAt8425UXQ43oehMK4g9N7Fs',
    appId: '1:144680558728:ios:991b631ecab9ff6b557f3d',
    messagingSenderId: '144680558728',
    projectId: 'widgetmaster999',
    databaseURL: 'https://widgetmaster999-default-rtdb.firebaseio.com',
    storageBucket: 'widgetmaster999.appspot.com',
    iosClientId: '144680558728-qe5btdn6rvguhh0c651ammtj8c6oouoj.apps.googleusercontent.com',
    iosBundleId: 'com.widget.iosmaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6_sfCoPdtAt8425UXQ43oehMK4g9N7Fs',
    appId: '1:144680558728:ios:d6f2883f20ccaa6d557f3d',
    messagingSenderId: '144680558728',
    projectId: 'widgetmaster999',
    databaseURL: 'https://widgetmaster999-default-rtdb.firebaseio.com',
    storageBucket: 'widgetmaster999.appspot.com',
    iosClientId: '144680558728-rh1pqn4khd7t9eevk4203orfvarecrhl.apps.googleusercontent.com',
    iosBundleId: 'com.widget.macmaster',
  );
}
